default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: sample_postgres_development

test:
  <<: *default
  adapter: postgresql
  database: sample_postgres_development

production:
  <<: *default
