default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: inviter_development

test:
  <<: *default
  adapter: postgresql
  database: inviter_test

production:
  <<: *default
